package com.poker.enumeration;

public enum GameEvent {
    HOST_IS_READY,
    START_NEXT_ROUND,
    ROUND_STARTED,
    PLAYER_ACTION_APPLIED,
    PLAYER_ACTION_RECEIVED,
    ROUND_STATE_ADVANCED,
    GAME_OVER,
    PLAYER_DISCONNECTED,
    PLAYER_TURN_TIMED_OUT,
    PLAYER_TIMEOUT_PROCESSED;
}
