name: Deploy to AWS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

env:
  AWS_REGION: ca-central-1
  IMAGE_NAME: java-poker
  TAG: latest
  ECR_REGISTRY: 235772044469.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  id-token: write
  contents: read

jobs:
  dockerize-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:

          role-to-assume: arn:aws:iam::235772044469:role/GitHubActions-ECRPushRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag docker image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to ec2 via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

            docker pull $IMAGE_URI

            docker stop java-poker || true
            docker rm java-poker || true

            docker run -d \
              --name java-poker \
              -p 8080:8080 \
              $IMAGE_URI
