name: Deploy to AWS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ca-central-1
  IMAGE_NAME: java-poker
  TAG: latest
  ECR_REGISTRY: 235772044469.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  id-token: write
  contents: read

jobs:
  dockerize-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug
        shell: bash
        run: |
          echo "Fetching OIDC token..."
          curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
          | jq -R 'split(".") | .[1] | @base64d | fromjson' \
          | jq .sub

      - name: Configure AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:

          role-to-assume: arn:aws:iam::235772044469:role/GitHubActions-ECRPushRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
